config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

  root 'users#new'

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates_presence_of :name, :band_id
  validates :live_album, inclusion: { in: [true, false] }

  belongs_to :band

  has_many :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates_presence_of :name, :album_id
  validates :bonus_track, inclusion: { in: [true, false] }

  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def self.find_by_credentials(username, password)
    return unless user = User.find_by_username(username)
    user if user.is_password?(password)
  end

  def get_new_session_token
    token = nil
    until token && User.find_by_session_token(token).nil?
      token = SecureRandom::urlsafe_base64(16)
    end
    self.session_token = token
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :find_by_id, only: [:destroy, :edit, :show, :update]

  def create
    @album = Album.new(album_params)
    if @album.save
      flash.now[:messages] = "You have successfully generated an album."
      redirect_to band_url(@album.band)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def new
    @album = Album.new
    @album.band_id = params[:band_id]
  end

  def edit
  end

  def show
  end

  def update
    if @album.update(album_params)
      flash[:messages] = ["Album Updated!"]
      redirect_to @album
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @album.destroy
      flash[:messages] = ["Album Deleted!"]
      redirect_to band_url(@album.band)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :show
    end
  end

  private

  def find_by_id
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:name, :band_id, :live_album)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  def login_user!
    session[:token] = @user.get_new_session_token
    @user.save
    redirect_to bands_url    
  end

  def current_user
    User.find_by_session_token(session[:token])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

  def require_login
    unless current_user
      redirect_to new_session_url
    end
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :find_by_id, only: [:destroy, :edit, :show, :update]

  def index
    @bands = Band.all
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash.now[:messages] = ["You have successfully generated a band."]
      redirect_to bands_url 
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    @band = Band.new
  end

  def edit
  end

  def show
  end

  def update
    if @band.update(band_params)
      flash[:messages] = ["Band Updated!"]
      redirect_to @band
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @band.destroy
      flash[:messages] = ["Band Deleted!"]
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :show
    end
  end

  private

  def find_by_id
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])
    if @user
      login_user!
    else
      flash.now[:errors] = "Invalid username and/or password!!"
      @user = User.new(user_params)
      render :new
    end
  end

  def destroy
    user = current_user
    user.get_new_session_token
    user.save
    session[:token] = nil
  end

  private

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :find_by_id, only: [:edit, :show, :update, :destroy]

  def create
    @track = Track.new(track_params)
    @track
    if @track.save
      flash.now[:messages] = "You have successfully generated a track."
      redirect_to album_url(@track.album)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def new
    @track = Track.new
    @track.album_id = params[:album_id]
  end

  def edit
  end

  def show
  end

  def update
    if @track.update(track_params)
      flash[:messages] = ["Track Updated!"]
      redirect_to @track
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @track.destroy
      flash[:messages] = ["Track Deleted!"]
      redirect_to album_url(@track.album)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :show
    end
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id, :bonus_track, :lyrics)
  end

  def find_by_id
    @track = Track.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.get_new_session_token
    if @user.save
      login_user!
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def csrf_token
    (<<-HTML).html_safe
      <input type="hidden"
            name="authenticity_token"
            value="#{ form_authenticity_token }">
    HTML
  end

  def the_url(obj)
    Rails.application.routes.url_helpers.send(obj.class.name.parameterize + "_path", obj.id)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_album_form.html.erb
<% action = album.persisted? ? album_url(album) : albums_url %>

<form class="album_form" action="<%= action %>" method="post">
  <%= csrf_token %>

  <% if album.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>Name <input type="text" name="album[name]" value="<%= album.name %>"></label>
  <br>
  <label for="band">Band</label>
  <select name="album[band_id]" id="band">
    <option>--Select A Band--</option>
    <% Band.all.each do |band| %>
      <option value=<%= band.id %> <%= 'selected' if band.id == album.band_id %>>
        <%= band.name %>
      </option>
    <% end %>
  </select>
  <br>
  <label>Live Album
    <input type="radio" name="album[live_album]" value="true"<%= "checked" if album.live_album %>>
  </label>
  <label>Studio Album
    <input type="radio" name="album[live_album]" value="false"<%= "checked" if album.live_album == false %>>
  </label>
  <br>
  <input type="submit" value="submit">
</form>

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/edit.html.erb
<h1>Edit Album Details - <%= @album.name %></h1>
<br>
<%= render 'album_form', album: @album %>

app/views/albums/new.html.erb
<h1>Create a new album</h1>
<br>
<%= render 'album_form', album: @album %>

app/views/albums/show.html.erb
<h1> <%= @album.name %>, <%= "a live album " if @album.live_album %>by <%= @album.band.name %> </h1>

<%= button_to "Edit Album Details", edit_album_url(@album), method: :get %>

<h3> Tracklist: </h3>

<%= render 'shared/list_of_things', things: @album.tracks, parent_thing: "album", thing_class: "track", parent_thing_id: @album.id %>

<br>

<%= button_to "Back to albums", band_url(@album.band), method: :get %>

app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

app/views/bands/_band_form.html.erb
<% action = band.persisted? ? band_url(band) : bands_url %>

<form class="band name" action="<%= action %>" method="post">
  <%= csrf_token %>
  <% if band.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>Name:
    <input type="text" name="band[name]" value=<%= @band.name %>>
  </label>
  <input type="submit" name="submit" value="Submit">
</form>

app/views/bands/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

app/views/bands/edit.html.erb
<h1>Edit Band Name</h1>
<br>

<%= render "band_form", band: @band %>

app/views/bands/index.html.erb
<h1>All The Bands</h1>

<%= render 'shared/list_of_things', things: @bands, parent_thing: nil, parent_thing_id: nil, thing_class: "band" %>

app/views/bands/new.html.erb
<h1>Create a New Band</h1>
<br>
<%= render 'band_form', band: @band%>

app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>

<%= button_to "Change Band Name", edit_band_url(@band) %>

<h3> Albums: </h3>

<%= render 'shared/list_of_things', things: @band.albums, parent_thing: "band", parent_thing_id: @band.id, thing_class: "album" %>

<%= button_to "Back to Bands", bands_url, method: :get %>

app/views/bands/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LabelMate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h3> <%= link_to "Join", new_user_url %> <%= link_to "Log in", new_session_url %> </h3>

<% flash.each do |name, msg| %>
  <% msg.each do |m| %>
    <%= content_tag :div, m , name: "name" %>
  <% end %>
<% end %>


<%= yield %>

</body>
</html>

app/views/shared/_list_of_things.html.erb
<% if things %>
  <% things.each do |thing| %>
    <div>
      <%= link_to thing.name, the_url(thing) %>
      <%= button_to "Delete", the_url(thing), method: :delete, data: { confirm: "Delete this #{thing_class}?" } %>
    </div>
    <br>
  <% end %>
<% end %>
<%= button_to "Add a #{thing_class}", Rails.application.routes.url_helpers.send("new_#{(parent_thing ? parent_thing + "_" : "") + thing_class}_path".to_sym, parent_thing_id), method: :get %>

app/views/shared/_login.html.erb
<form class="user_form" action= <%= new_user ? user_url : session_url %> method="post">
  <%= csrf_token %>
  <label> Username:
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <br>
  <% if new_user %>
    <label> Email:
      <input type="text" name="user[email]" value="<%= @user.email %>">
    </label>
    <br>
  <% end %>
  <label> Password
    <input type="password" name="user[password]" value="">
  </label>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/tracks/_track_form.html.erb
<% action = track.persisted? ? track_url(track) : tracks_url %>

<form class="track_form" action="<%= action %>" method="post">
  <%= csrf_token %>
  <% if track.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>Name <input type="text" name="track[name]" value="<%= track.name %>"></label>
  <br>
  <label for="album">Album</label>
  <select name="track[album_id]" id="album">
    <option>Select an album</option>
    <% Album.all.each do |album| %>
      <option value=<%= album.id %> <%= 'selected' if album.id == track.album_id %>>
        <%= album.name %>
      </option>
    <% end %>
  </select>
  <br>
  <label>Bonus Track<input type="radio" name="track[bonus_track]" value=true <%= "checked" if track.bonus_track %>></label>
  <label>Regular Track<input type="radio" name="track[bonus_track]" value=false<%= "checked" if !track.bonus_track %>></label>
  <br>
  Lyrics:
  <br>
  <textarea name="track[lyrics]" rows="20" cols="50" value=""></textarea>
  <input type="submit" value="submit">
</form>

app/views/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

app/views/tracks/destroy.html.erb
<h1>Tracks#destroy</h1>
<p>Find me in app/views/tracks/destroy.html.erb</p>

app/views/tracks/edit.html.erb
<h1>Edit Track Details - <%= @track.name %></h1>
<br>
<%= render 'track_form', track: @track %>

app/views/tracks/new.html.erb
<h1>Create a New Track</h1>
<br>
<%= render 'track_form', track: @track %>

app/views/tracks/show.html.erb
<h1> <%= "#{@track.name} - #{@track.album.band.name}: #{@track.album.name}" %> </h1>
<br>
<h3> <%= "Bonus Track" if @track.bonus_track %> </h3>
<br>
<br>
<h2>Lyrics:</h2>
<br>
<%= @track.lyrics %>
<br>
<%= button_to "Edit Track Details", edit_track_url(@track), method: :get %>
<br>
<%= button_to "Back to Tracklist", album_url(@track.album), method: :get %>

app/views/tracks/update.html.erb
<h1>Tracks#update</h1>
<p>Find me in app/views/tracks/update.html.erb</p>

app/views/users/new.html.erb
<h1> Sign up! </h1>

<%= render 'shared/login', user: @user, new_user: true %>